version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    env_file:
      - stack.env #optional
    ports:
      - ${PORT_1}:5800
    volumes:
      - /mnt/user/appdata/jdownloader/config:/config:rw
      - /mnt/user/Download:/output:rw